# -*- coding: utf-8 -*-
"""first_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BaEDlzZzv4wsd20dkPIA5bWB9Plbs_Pd
"""

!pip install biopython

from google.colab import files
uploaded = files.upload()

from Bio import SeqIO
for record in SeqIO.parse("gene.fna","fasta"):
  print(record.id)
  print(record.seq)

from Bio import SeqIO

for record in SeqIO.parse("gene.fna","fasta"):
  print(record.id,len(record.seq))

from Bio.SeqUtils import gc_fraction

for record in SeqIO.parse("gene.fna","fasta"):
  print(record.id,gc_fraction(record.seq)*100)

from Bio import SeqIO
for record in SeqIO.parse("gene.fna","fasta"):
  print("original seq:",record.seq)
  print("reverse:", record.seq.reverse_complement())

from Bio import SeqIO
for record in SeqIO.parse("gene.fna","fasta"):
  print("dna:",record.seq)
  print("protein:",record.seq.translate())

from Bio import SeqIO
from Bio.SeqRecord import SeqRecord

record=[]

for record in SeqIO.parse("gene.fna","fasta"):
  rc=record.seq.reverse_complement()
  record.append(SeqRecord(rc,id=record.id))

  SeqIO.write(record,"reverse.fasta","fasta")

from google.colab import files
uploaded = files.upload()

from Bio import SeqIO
longest=0
name=""
for record in SeqIO.parse("gene.fna","fasta"):
  if len(record.seq)>longest:
    longest=len(record.seq)
    name=record.id

print(name,longest)

from Bio import SeqIO
for record in SeqIO.parse("gene.fna","fasta"):
  seq=record.seq
  print(record.id)
  print("A",seq.count("A"))
  print("T",seq.count("T"))
  print("G",seq.count("G"))
  print("C",seq.count("C"))

1.count the number seq in your file

2. print first 100 bases from your sequence